### ISSUE TITLE
Cannot create folder in WORKDIR

### ISSUE THREAD

**Issue by duongsieu** [TrafeX/docker-php-nginx#132]
I can not run composer i or mkdir folder in docker container. It show message: permisson define. I change user to root then can create but php-fpm.sock error. Please help me

**Comment by TrafeX** [comment]
Hi @duongsieu,

You should be able to create folder in the `/var/www/html` folder since that folder is owned by the `nobody` user (as long as this folder isn't mounted to a different filesystem).
You can also temporary switch to `root` and back to `nobody` after you have set the correct permissions, example;

```Dockerfile

FROM trafex/php-nginx

USER root

RUN mkdir /some/folder

USER nobody
```

**Comment by TrafeX** [comment]
I assume this issue is resolved. If not, please let me know!

**Comment by sieu-duong** [comment]
@TrafeX thanks your support. I resolved issue
