### ISSUE TITLE
Version mismatch (latest !=3.5.0

### ISSUE THREAD

**Issue by Mugane** [TrafeX/docker-php-nginx#176]
Please could you make the "latest" tag correspond to the latest stable release, rather than a dynamic non-versioned working copy? The version tagged "latest" in the [Docker hub](https://hub.docker.com/r/trafex/php-nginx/tags) has commits that are far more recent than the real latest versioned release (3.5.0). Also where is the change log (is there one)? Thanks!

**Comment by TrafeX** [comment]
Hi @Mugane,

The `latest` tag is automatically updated every week with the latest patches from Alpine Linux.
It's the unstable version basically because it's not fully tested. The stable releases are tagged and the changelogs can be found under [Releases](https://github.com/TrafeX/docker-php-nginx/releases).
I don't have the intention to change this, but I will make this more clear in the README so you know what to expect.

**Comment by Mugane** [comment]
Ah, gotcha. I thought the convention was to have the "latest" tag correspond to the most recent stable release. I guess it doesn't matter if as you mention it's documented. Thanks!

**Comment by TrafeX** [comment]
It's a common practice indeed. But this project is a bit different since it's goal is to act as an example what you can change to your needs.
I've added it to the README: https://github.com/TrafeX/docker-php-nginx?tab=readme-ov-file#versioning
