### ISSUE TITLE
add ENV vars to nginx

### ISSUE THREAD

**Issue by sunuazizrahayu** [TrafeX/docker-php-nginx#34]
would you like to tell me how to add ENV variables to nginx.conf?
i wanna add **APP_URL** where value is my domain address, so my php can read these vars.
it work if i ran with php:7.3-alpine (without nginx).
thanks

**Comment by TrafeX** [comment]
Hi @sunuazizrahayu,

You should pass the environment variable to Docker like this
`docker run -e "APP_URL=https://example.org" trafex/alpine-nginx-php7`
These env variables should become available in `$_ENV`

**Comment by fagiani** [comment]
Hi @sunuazizrahayu 

Not sure if I'm too late to the party but `nginx` config files won't accept shell environment variables to be interpreted at runtime as it has its own environment variables.

I've had to tweak a bit to achieve that at the container boot time and additionally to setting the `APP_URL` flag proposed by @TrafeX on the `docker run` command above, you'd have to create a placeholder on your `config/nginx.conf` template with something like `{{appURL}}` where you want it to be replaced and then get the `Dockerfile` to use this `CMD` instead of the default:

    CMD sed -i "s|{{appURL}}|$APP_URL|g" /etc/nginx/nginx.conf && \
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

Please notice I'm using a different placeholder notation with braces/brackets mainly to avoid conflict with native `nginx` variables syntax.

I hope that becomes helpful to you and others in the future.

Keep rocking!

**Comment by sunuazizrahayu** [comment]
Hello @fagiani ,
i don't know why, those command won't replace ``{{appURL}}`` on my nginx.conf

**Comment by fagiani** [comment]
@sunuazizrahayu As I've mentioned before, the replacement should happen at runtime right before the container starts the `supervisord`. It is important you replace the `CMD` within the `Dockerfile` and the `conf/nginx.conf` and build the docker container beforehand and then use the `docker run` proposed by @TrafeX . I could take a brief look at it If you would like. For that, please share your fork.

**Comment by sunuazizrahayu** [comment]
@fagiani i'm sorry.. on my comment before, i've changed my ```config/nginx.conf```` and ```Dockerfile``` too. Temporary solution i use @TrafeX 's [solution](https://github.com/TrafeX/docker-php-nginx/issues/34#issuecomment-622747869), but i need solution what you tell @fagiani .

**Comment by fagiani** [comment]
@sunuazizrahayu please take a look at [this server fault](https://serverfault.com/questions/577370/how-can-i-use-environment-variables-in-nginx-conf) thread and pay close attention on the solutions proposed. I've taken my approach from there. If you want me to take a brief look please share your files.

Hope it helps.
