### ISSUE TITLE
/bin/sh: docker-php-ext-enable: not found

### ISSUE THREAD

**Issue by yunus89** [TrafeX/docker-php-nginx#36]
When i try add in Dockerfile

    COPY opencensus/* /tmp/opencensus/

    RUN cd /tmp/opencensus \
        && phpize \
        && ./configure --enable-opencensus \
        && make -j "$(nproc)" \
        && make install \
        && cd ~ \
        && rm -r /tmp/opencensus \
        && docker-php-ext-enable opencensus

i get an error saying `docker-php-ext-enable` is not found. I expected it to be part of php installed in this image.

How can i make `docker-php-ext-enable` available ?

**Comment by TrafeX** [comment]
Hi @yunus89,

`docker-php-ext-enable` is not part of this image because most extensions can be installed as precompiled packages from Alpine Linux: https://pkgs.alpinelinux.org/packages?name=php7*&branch=v3.11
If the extension you're looking for is not there like in this case, you can manually install the extension and enable it with;
```
RUN echo "extension=opencensus.so" > /etc/php7/conf.d/opencensus.ini
```
That's what `docker-php-ext-enable` does for you.

**Comment by yunus89** [comment]
Hi @TrafeX ,

Wow, thanks for the quick reply, i will definately try this

**Comment by yunus89** [comment]
@TrafeX 

This solution worked, thanks
