### ISSUE TITLE
Run very slow on cloud run

### ISSUE THREAD

**Issue by kientv** [TrafeX/docker-php-nginx#64]
I have tried to launch WordPress on Google Cloud Run (Memory 4GiB and 4 vCPU), but It's very slow, about more than 10 seconds on each request.

**Comment by TrafeX** [comment]
Hi @kientv,

Honestly I've no idea what could cause this. I'm running this container in multiple production environments and never experienced these response times you're mentioning.
My guess would be that it's caused by the code you're running in the container. Maybe it calls an external API or database?

**Comment by kientv** [comment]
That's right, database and cloud run should same region.
